// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQNhJ67AMuBVue2IYpyFzmWZxd8_Nxls',
    appId: '1:145579150656:web:748040343fd0cdaa01fea5',
    messagingSenderId: '145579150656',
    projectId: 'krs-app-notifications-1',
    authDomain: 'krs-app-notifications-1.firebaseapp.com',
    storageBucket: 'krs-app-notifications-1.firebasestorage.app',
    measurementId: 'G-W65VHPXWMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeLtxEgsAwV-oZo0FTk_mZm3lGq-HsQaA',
    appId: '1:145579150656:android:fca864647b07a4fe01fea5',
    messagingSenderId: '145579150656',
    projectId: 'krs-app-notifications-1',
    storageBucket: 'krs-app-notifications-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIqUOAbnhlwxkN8uc3mZ2HuhofRUTucvE',
    appId: '1:145579150656:ios:13c5d6eefb37ca5e01fea5',
    messagingSenderId: '145579150656',
    projectId: 'krs-app-notifications-1',
    storageBucket: 'krs-app-notifications-1.firebasestorage.app',
    iosBundleId: 'com.example.krsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIqUOAbnhlwxkN8uc3mZ2HuhofRUTucvE',
    appId: '1:145579150656:ios:13c5d6eefb37ca5e01fea5',
    messagingSenderId: '145579150656',
    projectId: 'krs-app-notifications-1',
    storageBucket: 'krs-app-notifications-1.firebasestorage.app',
    iosBundleId: 'com.example.krsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSQNhJ67AMuBVue2IYpyFzmWZxd8_Nxls',
    appId: '1:145579150656:web:6b25d152da27bbab01fea5',
    messagingSenderId: '145579150656',
    projectId: 'krs-app-notifications-1',
    authDomain: 'krs-app-notifications-1.firebaseapp.com',
    storageBucket: 'krs-app-notifications-1.firebasestorage.app',
    measurementId: 'G-YQF1KRH6T9',
  );
}
