// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGMvfTcJWSZN94oNQCcYyDq46Qu8HllJ0',
    appId: '1:1050948668120:web:0e46a399dfe03acebb65ad',
    messagingSenderId: '1050948668120',
    projectId: 'krs-workspace-app',
    authDomain: 'krs-workspace-app.firebaseapp.com',
    storageBucket: 'krs-workspace-app.firebasestorage.app',
    measurementId: 'G-FLVC566WY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkgCKw6LX6YN0iYeCaTFMAK1E8MXqFrfI',
    appId: '1:1050948668120:android:efdddaa008156dd4bb65ad',
    messagingSenderId: '1050948668120',
    projectId: 'krs-workspace-app',
    storageBucket: 'krs-workspace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUbyy0WO-MwwXLRMG-5sRnc7VkH4DKsYU',
    appId: '1:1050948668120:ios:e19579bfb5d3d4e1bb65ad',
    messagingSenderId: '1050948668120',
    projectId: 'krs-workspace-app',
    storageBucket: 'krs-workspace-app.firebasestorage.app',
    iosBundleId: 'com.krs.krsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUbyy0WO-MwwXLRMG-5sRnc7VkH4DKsYU',
    appId: '1:1050948668120:ios:c243e88d3af7b5eebb65ad',
    messagingSenderId: '1050948668120',
    projectId: 'krs-workspace-app',
    storageBucket: 'krs-workspace-app.firebasestorage.app',
    iosBundleId: 'com.krs.krsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGMvfTcJWSZN94oNQCcYyDq46Qu8HllJ0',
    appId: '1:1050948668120:web:68673ce9e1e49262bb65ad',
    messagingSenderId: '1050948668120',
    projectId: 'krs-workspace-app',
    authDomain: 'krs-workspace-app.firebaseapp.com',
    storageBucket: 'krs-workspace-app.firebasestorage.app',
    measurementId: 'G-HXP92069V0',
  );
}
